'use client';

import { Check, Eye, Gauge, Monitor, Palette, RotateCcw, Sparkles, Type, WandSparkles } from 'lucide-react';
import { useTheme, type ColorTheme, type FontPairing, type RadiusStyle, type UiScale, type MotionPreference, type ContrastPreference, type SurfaceStyle, type CardDensity } from '@/components/theme-provider';

const colors: Array<{ id: ColorTheme; label: string; swatch: string; detail: string }> = [
  { id: 'gold', label: 'Gold', swatch: '#C9A961', detail: 'Warm editorial' }, { id: 'emerald', label: 'Emerald', swatch: '#34A876', detail: 'Calm + fresh' }, { id: 'sapphire', label: 'Sapphire', swatch: '#3E6FD9', detail: 'Focused + crisp' }, { id: 'rose', label: 'Rose', swatch: '#C97A8B', detail: 'Soft + expressive' }, { id: 'monochrome', label: 'Mono', swatch: '#B8B8B8', detail: 'Minimal + neutral' }, { id: 'custom', label: 'Custom', swatch: 'var(--color-primary-500)', detail: 'Your own palette' },
];
const fonts: Array<{ id: FontPairing; label: string; sample: string }> = [{ id: 'elegant', label: 'Elegant', sample: 'Playfair + Inter' }, { id: 'modern', label: 'Modern', sample: 'Space Grotesk + Inter' }, { id: 'classic', label: 'Classic', sample: 'Merriweather + Inter' }, { id: 'rounded', label: 'Rounded', sample: 'Poppins + Inter' }];
const radii: Array<{ id: RadiusStyle; label: string }> = [{ id: 'sharp', label: 'Sharp' }, { id: 'rounded', label: 'Rounded' }, { id: 'pill', label: 'Pill' }];
const scales: Array<{ id: UiScale; label: string; detail: string }> = [{ id: 'compact', label: 'Compact', detail: 'Tighter workspace' }, { id: 'comfortable', label: 'Comfortable', detail: 'Balanced spacing' }, { id: 'large', label: 'Large', detail: 'Larger controls' }];
const motions: Array<{ id: MotionPreference; label: string; detail: string }> = [{ id: 'full', label: 'Full motion', detail: 'Use NovaTools transitions' }, { id: 'reduced', label: 'Reduced motion', detail: 'Minimize animation' }];
const contrasts: Array<{ id: ContrastPreference; label: string; detail: string }> = [{ id: 'standard', label: 'Standard', detail: 'Balanced contrast' }, { id: 'high', label: 'High contrast', detail: 'Stronger text and focus' }];
const surfaces: Array<{ id: SurfaceStyle; label: string; detail: string }> = [{ id: 'clean', label: 'Clean', detail: 'Flat, crisp workspace' }, { id: 'textured', label: 'Textured', detail: 'Subtle background texture' }];
const densities: Array<{ id: CardDensity; label: string; detail: string }> = [{ id: 'relaxed', label: 'Relaxed', detail: 'More breathing room' }, { id: 'dense', label: 'Dense', detail: 'More content at once' }];

function ChoiceCard({ selected, onClick, children, detail }: { selected: boolean; onClick: () => void; children: React.ReactNode; detail?: string }) {
  return <button type="button" onClick={onClick} className={`nova-choice group relative rounded-xl p-4 text-left ${selected ? 'is-selected' : ''}`}><span className="flex items-center justify-between gap-3 text-sm font-semibold"><span>{children}</span>{selected && <Check className="h-4 w-4 text-primary-500" />}</span>{detail && <span className="nova-muted mt-1 block text-xs leading-5">{detail}</span>}</button>;
}
function Section({ icon: Icon, title, detail, children }: { icon: typeof Monitor; title: string; detail: string; children: React.ReactNode }) {
  return <section className="nova-settings-card rounded-2xl p-5 sm:p-6"><div className="mb-6 flex items-start gap-3"><div className="nova-icon-box flex h-10 w-10 shrink-0 items-center justify-center rounded-xl"><Icon className="h-4 w-4" /></div><div><h2 className="text-lg font-semibold">{title}</h2><p className="nova-muted mt-0.5 text-sm leading-5">{detail}</p></div></div>{children}</section>;
}

const previewStyles = `
.nova-settings-card{background:rgb(var(--surface-panel)/.88);border:1px solid rgb(var(--color-border)/.09);box-shadow:0 18px 50px -34px rgb(var(--shadow-color)/.5);backdrop-filter:blur(16px)}
.nova-choice{display:block;width:100%;background:rgb(var(--surface-control)/.72);border:1px solid rgb(var(--color-border)/.1);color:rgb(var(--color-text-primary));transition:background-color .18s ease,border-color .18s ease,box-shadow .18s ease,transform .18s ease}
.nova-choice:hover{background:rgb(var(--surface-control-hover));border-color:rgb(var(--color-primary-500)/.3);transform:translateY(-1px)}
.nova-choice.is-selected{background:rgb(var(--color-primary-500)/.09);border-color:rgb(var(--color-primary-500)/.55);box-shadow:0 8px 24px -18px rgb(var(--color-primary-500)/.7)}
.nova-color-choice{display:flex;align-items:center;gap:.7rem;min-width:0;border:1px solid rgb(var(--color-border)/.1);background:rgb(var(--surface-control)/.72);border-radius:.8rem;padding:.65rem;transition:all .18s ease;color:rgb(var(--color-text-primary))}
.nova-color-choice:hover{background:rgb(var(--surface-control-hover));border-color:rgb(var(--color-primary-500)/.3);transform:translateY(-1px)}
.nova-color-choice.is-selected{background:rgb(var(--color-primary-500)/.09);border-color:rgb(var(--color-primary-500)/.55)}
.nova-icon-box{background:rgb(var(--color-primary-500)/.1);color:rgb(var(--color-primary-600));box-shadow:inset 0 0 0 1px rgb(var(--color-primary-500)/.08)}
.dark .nova-icon-box{color:rgb(var(--color-primary-400))}
.nova-preview{background:linear-gradient(145deg,rgb(var(--surface-panel-muted)),rgb(var(--surface-control)));border:1px solid rgb(var(--color-border)/.09);box-shadow:inset 0 1px 0 rgb(255 255 255/.04)}
@media(max-width:639px){.nova-color-choice{padding:.55rem}.nova-choice{padding:.8rem}}
`;

export default function CustomizePage() {
  const { theme, toggleTheme, resetPreferences, colorTheme, setColorTheme, customColors, setCustomColors, fontPairing, setFontPairing, radiusStyle, setRadiusStyle, uiScale, setUiScale, motionPreference, setMotionPreference, contrastPreference, setContrastPreference, surfaceStyle, setSurfaceStyle, cardDensity, setCardDensity } = useTheme();
  const currentColor = colors.find((c) => c.id === colorTheme);

  return <main className="nova-page min-h-[calc(100vh-4rem)]">
    <style>{previewStyles}</style>
    <div className="relative overflow-hidden"><div className="pointer-events-none absolute inset-x-0 top-0 h-80 nova-grid opacity-70" /><div className="pointer-events-none absolute left-1/2 top-0 h-72 w-72 -translate-x-1/2 rounded-full bg-primary-500/10 blur-3xl" />
      <div className="relative mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8 lg:py-14">
        <header className="mb-10 max-w-3xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-primary-500/20 bg-primary-500/10 px-3 py-1.5 text-xs font-semibold text-primary-600 dark:text-primary-400"><WandSparkles className="h-3.5 w-3.5" /> Personalize NovaTools</div><h1 className="text-4xl font-bold tracking-tight sm:text-5xl">Make the workspace <span className="nova-gradient-text">yours.</span></h1><p className="nova-muted mt-4 max-w-2xl text-base leading-7">Tune the visual language of NovaTools. Every preference is saved on this device and applied consistently across the website.</p></header>
        <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_300px]">
          <div className="space-y-5">
            <Section icon={Monitor} title="Appearance" detail="Set the base mode and the accent that defines the interface."><div className="grid gap-3 sm:grid-cols-2"><ChoiceCard selected={theme === 'light'} onClick={() => theme === 'dark' && toggleTheme()} detail="Bright surfaces with clear dark text">Light mode</ChoiceCard><ChoiceCard selected={theme === 'dark'} onClick={() => theme === 'light' && toggleTheme()} detail="Deep surfaces with softened contrast">Dark mode</ChoiceCard></div><h3 className="mb-3 mt-7 text-sm font-semibold">Color system</h3><div className="grid grid-cols-2 gap-2.5 sm:grid-cols-3">{colors.map((item) => <button key={item.id} type="button" onClick={() => setColorTheme(item.id)} className={`nova-color-choice ${colorTheme === item.id ? 'is-selected' : ''}`}><span className="h-7 w-7 shrink-0 rounded-lg" style={{ background: item.id === 'custom' ? 'linear-gradient(135deg,rgb(var(--color-primary-400)),rgb(var(--color-secondary-500)))' : item.swatch }} /><span className="min-w-0 flex-1 text-left"><span className="block text-xs font-semibold">{item.label}</span><span className="nova-muted block truncate text-[10px]">{item.detail}</span></span>{colorTheme === item.id && <Check className="h-3.5 w-3.5 text-primary-500" />}</button>)}</div>{colorTheme === 'custom' && <div className="nova-surface-muted mt-4 rounded-xl p-4"><div className="grid gap-3 sm:grid-cols-3">{(['primary','secondary','accent'] as const).map((key) => <label key={key} className="text-xs font-semibold capitalize">{key}<input type="color" value={customColors[key]} onChange={(e) => setCustomColors({ ...customColors, [key]: e.target.value })} className="mt-2 h-11 w-full cursor-pointer rounded-lg border-0 bg-transparent p-0" /></label>)}</div></div>}</Section>
            <Section icon={Type} title="Typography & shape" detail="Give NovaTools the personality and geometry you prefer."><h3 className="mb-3 text-sm font-semibold">Font pairing</h3><div className="grid gap-3 sm:grid-cols-2">{fonts.map((item) => <ChoiceCard key={item.id} selected={fontPairing === item.id} onClick={() => setFontPairing(item.id)} detail={item.sample}>{item.label}</ChoiceCard>)}</div><h3 className="mb-3 mt-7 text-sm font-semibold">Corner style</h3><div className="grid grid-cols-3 gap-3">{radii.map((item) => <ChoiceCard key={item.id} selected={radiusStyle === item.id} onClick={() => setRadiusStyle(item.id)}>{item.label}</ChoiceCard>)}</div></Section>
            <Section icon={Gauge} title="Layout & interaction" detail="Control density, scale and motion without changing functionality."><h3 className="mb-3 text-sm font-semibold">UI scale</h3><div className="grid gap-3 sm:grid-cols-3">{scales.map((item) => <ChoiceCard key={item.id} selected={uiScale === item.id} onClick={() => setUiScale(item.id)} detail={item.detail}>{item.label}</ChoiceCard>)}</div><h3 className="mb-3 mt-7 text-sm font-semibold">Card density</h3><div className="grid gap-3 sm:grid-cols-2">{densities.map((item) => <ChoiceCard key={item.id} selected={cardDensity === item.id} onClick={() => setCardDensity(item.id)} detail={item.detail}>{item.label}</ChoiceCard>)}</div><h3 className="mb-3 mt-7 text-sm font-semibold">Motion</h3><div className="grid gap-3 sm:grid-cols-2">{motions.map((item) => <ChoiceCard key={item.id} selected={motionPreference === item.id} onClick={() => setMotionPreference(item.id)} detail={item.detail}>{item.label}</ChoiceCard>)}</div></Section>
            <Section icon={Eye} title="Accessibility & surfaces" detail="Keep the interface comfortable, readable and predictable."><h3 className="mb-3 text-sm font-semibold">Contrast</h3><div className="grid gap-3 sm:grid-cols-2">{contrasts.map((item) => <ChoiceCard key={item.id} selected={contrastPreference === item.id} onClick={() => setContrastPreference(item.id)} detail={item.detail}>{item.label}</ChoiceCard>)}</div><h3 className="mb-3 mt-7 text-sm font-semibold">Background surface</h3><div className="grid gap-3 sm:grid-cols-2">{surfaces.map((item) => <ChoiceCard key={item.id} selected={surfaceStyle === item.id} onClick={() => setSurfaceStyle(item.id)} detail={item.detail}>{item.label}</ChoiceCard>)}</div></Section>
            <div className="flex justify-end pt-1"><button type="button" onClick={resetPreferences} className="nova-control inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold"><RotateCcw className="h-4 w-4" /> Reset preferences</button></div>
          </div>
          <aside className="h-fit lg:sticky lg:top-24"><div className="nova-settings-card rounded-2xl p-5"><div className="flex items-center justify-between"><div><p className="nova-eyebrow">Live system</p><h2 className="mt-1 text-lg font-semibold">Preview</h2></div><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary-500/10 text-primary-500"><Palette className="h-4 w-4" /></span></div><div className="nova-preview mt-5 rounded-2xl p-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary-500/10"><Sparkles className="h-4 w-4 text-primary-500" /></span><div><div className="text-sm font-bold">NovaTools</div><div className="nova-muted text-[11px]">Your current setup</div></div></div><div className="mt-5 rounded-xl border border-primary-500/20 bg-primary-500/[0.07] p-4"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-primary-600 dark:text-primary-400">Accent</span><span className="h-2 w-2 rounded-full bg-primary-500" /></div><div className="mt-1 text-lg font-bold">{currentColor?.label ?? 'Custom'}</div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-primary-500/15"><div className="h-full w-2/3 rounded-full bg-primary-500" /></div></div><div className="mt-3 grid grid-cols-3 gap-2"><div className="nova-surface-muted rounded-lg p-2"><div className="text-[9px] uppercase tracking-wider nova-muted">Type</div><div className="mt-1 text-[10px] font-semibold capitalize">{fontPairing}</div></div><div className="nova-surface-muted rounded-lg p-2"><div className="text-[9px] uppercase tracking-wider nova-muted">Shape</div><div className="mt-1 text-[10px] font-semibold capitalize">{radiusStyle}</div></div><div className="nova-surface-muted rounded-lg p-2"><div className="text-[9px] uppercase tracking-wider nova-muted">Scale</div><div className="mt-1 text-[10px] font-semibold capitalize">{uiScale}</div></div></div></div><p className="nova-muted mt-4 text-xs leading-5">Preferences stay on this device. Reduced-motion settings are also respected.</p></div></aside>
        </div>
      </div>
    </div>
  </main>;
}
